// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: protoc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFulcrumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
}

func (x *GetFulcrumRequest) Reset() {
	*x = GetFulcrumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFulcrumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFulcrumRequest) ProtoMessage() {}

func (x *GetFulcrumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFulcrumRequest.ProtoReflect.Descriptor instead.
func (*GetFulcrumRequest) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{0}
}

func (x *GetFulcrumRequest) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *GetFulcrumRequest) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

type GetFulcrumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FulcrumAddress string `protobuf:"bytes,1,opt,name=fulcrum_address,json=fulcrumAddress,proto3" json:"fulcrum_address,omitempty"`
}

func (x *GetFulcrumResponse) Reset() {
	*x = GetFulcrumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFulcrumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFulcrumResponse) ProtoMessage() {}

func (x *GetFulcrumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFulcrumResponse.ProtoReflect.Descriptor instead.
func (*GetFulcrumResponse) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{1}
}

func (x *GetFulcrumResponse) GetFulcrumAddress() string {
	if x != nil {
		return x.FulcrumAddress
	}
	return ""
}

type PropagarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector   string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base     string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Enemigos int32  `protobuf:"varint,3,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
	Accion   string `protobuf:"bytes,4,opt,name=accion,proto3" json:"accion,omitempty"`
}

func (x *PropagarRequest) Reset() {
	*x = PropagarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropagarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagarRequest) ProtoMessage() {}

func (x *PropagarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagarRequest.ProtoReflect.Descriptor instead.
func (*PropagarRequest) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{2}
}

func (x *PropagarRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *PropagarRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *PropagarRequest) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

func (x *PropagarRequest) GetAccion() string {
	if x != nil {
		return x.Accion
	}
	return ""
}

type PropagarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PropagarResponse) Reset() {
	*x = PropagarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropagarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagarResponse) ProtoMessage() {}

func (x *PropagarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagarResponse.ProtoReflect.Descriptor instead.
func (*PropagarResponse) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{3}
}

func (x *PropagarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MergeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector      string       `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base        string       `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Enemigos    int32        `protobuf:"varint,3,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
	VectorClock *VectorClock `protobuf:"bytes,4,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{4}
}

func (x *MergeRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *MergeRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *MergeRequest) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

func (x *MergeRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type MergeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MergeResponse) Reset() {
	*x = MergeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResponse) ProtoMessage() {}

func (x *MergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResponse.ProtoReflect.Descriptor instead.
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{5}
}

func (x *MergeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ObtenerDatosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ObtenerDatosRequest) Reset() {
	*x = ObtenerDatosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObtenerDatosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerDatosRequest) ProtoMessage() {}

func (x *ObtenerDatosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerDatosRequest.ProtoReflect.Descriptor instead.
func (*ObtenerDatosRequest) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{6}
}

func (x *ObtenerDatosRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *ObtenerDatosRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type Registro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector   string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base     string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Enemigos int32  `protobuf:"varint,3,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
}

func (x *Registro) Reset() {
	*x = Registro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registro) ProtoMessage() {}

func (x *Registro) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registro.ProtoReflect.Descriptor instead.
func (*Registro) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{7}
}

func (x *Registro) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Registro) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Registro) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

type ObtenerDatosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registros   []*Registro  `protobuf:"bytes,1,rep,name=registros,proto3" json:"registros,omitempty"`
	VectorClock *VectorClock `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
}

func (x *ObtenerDatosResponse) Reset() {
	*x = ObtenerDatosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObtenerDatosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerDatosResponse) ProtoMessage() {}

func (x *ObtenerDatosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerDatosResponse.ProtoReflect.Descriptor instead.
func (*ObtenerDatosResponse) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{8}
}

func (x *ObtenerDatosResponse) GetRegistros() []*Registro {
	if x != nil {
		return x.Registros
	}
	return nil
}

func (x *ObtenerDatosResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type VectorClock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{9}
}

func (x *VectorClock) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VectorClock) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *VectorClock) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_protoc_proto protoreflect.FileDescriptor

var file_protoc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x59, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x63, 0x72,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x61, 0x73, 0x65, 0x22,
	0x3d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x71,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x63, 0x69, 0x6f,
	0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x8c, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x0b, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x29,
	0x0a, 0x0d, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x13, 0x4f, 0x62, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x08,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73,
	0x22, 0x7a, 0x0a, 0x14, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x6f, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x0b, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x37, 0x0a, 0x0b,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x7a, 0x32, 0x50, 0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12,
	0x46, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcb, 0x01, 0x0a, 0x0e, 0x46, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x70, 0x61, 0x67, 0x61, 0x72, 0x43, 0x61, 0x6d, 0x62, 0x69, 0x6f, 0x73, 0x12, 0x15, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x61, 0x67, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x05,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45,
	0x0a, 0x0c, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x12, 0x19,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protoc_proto_rawDescOnce sync.Once
	file_protoc_proto_rawDescData = file_protoc_proto_rawDesc
)

func file_protoc_proto_rawDescGZIP() []byte {
	file_protoc_proto_rawDescOnce.Do(func() {
		file_protoc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_proto_rawDescData)
	})
	return file_protoc_proto_rawDescData
}

var file_protoc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protoc_proto_goTypes = []interface{}{
	(*GetFulcrumRequest)(nil),    // 0: grpc.GetFulcrumRequest
	(*GetFulcrumResponse)(nil),   // 1: grpc.GetFulcrumResponse
	(*PropagarRequest)(nil),      // 2: grpc.PropagarRequest
	(*PropagarResponse)(nil),     // 3: grpc.PropagarResponse
	(*MergeRequest)(nil),         // 4: grpc.MergeRequest
	(*MergeResponse)(nil),        // 5: grpc.MergeResponse
	(*ObtenerDatosRequest)(nil),  // 6: grpc.ObtenerDatosRequest
	(*Registro)(nil),             // 7: grpc.Registro
	(*ObtenerDatosResponse)(nil), // 8: grpc.ObtenerDatosResponse
	(*VectorClock)(nil),          // 9: grpc.VectorClock
}
var file_protoc_proto_depIdxs = []int32{
	9, // 0: grpc.MergeRequest.vector_clock:type_name -> grpc.VectorClock
	7, // 1: grpc.ObtenerDatosResponse.registros:type_name -> grpc.Registro
	9, // 2: grpc.ObtenerDatosResponse.vector_clock:type_name -> grpc.VectorClock
	0, // 3: grpc.Broker.GetFulcrumAddress:input_type -> grpc.GetFulcrumRequest
	2, // 4: grpc.FulcrumService.PropagarCambios:input_type -> grpc.PropagarRequest
	4, // 5: grpc.FulcrumService.Merge:input_type -> grpc.MergeRequest
	6, // 6: grpc.FulcrumService.ObtenerDatos:input_type -> grpc.ObtenerDatosRequest
	1, // 7: grpc.Broker.GetFulcrumAddress:output_type -> grpc.GetFulcrumResponse
	3, // 8: grpc.FulcrumService.PropagarCambios:output_type -> grpc.PropagarResponse
	5, // 9: grpc.FulcrumService.Merge:output_type -> grpc.MergeResponse
	8, // 10: grpc.FulcrumService.ObtenerDatos:output_type -> grpc.ObtenerDatosResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protoc_proto_init() }
func file_protoc_proto_init() {
	if File_protoc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFulcrumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFulcrumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropagarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropagarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObtenerDatosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObtenerDatosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorClock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protoc_proto_goTypes,
		DependencyIndexes: file_protoc_proto_depIdxs,
		MessageInfos:      file_protoc_proto_msgTypes,
	}.Build()
	File_protoc_proto = out.File
	file_protoc_proto_rawDesc = nil
	file_protoc_proto_goTypes = nil
	file_protoc_proto_depIdxs = nil
}
